public class Main {
    public static void main(String[] args) {
        int [] ints1 = {1, 2, 3};
        int [] ints2 = {1, 2, 3, 4};
        int [] ints3 = {3, 2, 1};
        String [] strings1 = {"Hello", "World", "!"};
        String [] strings2 = {"I", "love", "APCSA"};
        String [] strings3 = {"Coding", "is", "cool"};
        int [] ints4 = {2, 3, 4};
        int [] ints5 = {-1, -2, -3};
        int [] ints6 = {1, 2, 3, 3, 4};
        int [] ints7 = {1, 0, -1};
        int [] ints8 = {1, 2, 3, 2};
        int [] ints9 = {1, 2, 1, 1, 1};
        int [] ints10 = {1, 2};
        int [] ints11 = {3, 4};
        String [] strings4 = {"zebra", "alpha"};
        double [] doubles1 = {2.0, 3.0, 4.0, 5.0};
        double [] doubles2 = {1.0, 2.0, 3.0, 4.0};
        double [] doubles3 = {3.0, 4.0, 5.0, 6.0};
        Algorithm.print(ints1);
        Algorithm.print(ints2);
        Algorithm.print(ints3);
        System.out.print("\n");
        Algorithm.swap(ints1, 0, 2);
        Algorithm.print(ints1);
            Algorithm.swap(ints1, 0, 2);
        Algorithm.swap(ints2, 1, 2);
        Algorithm.print(ints2);
            Algorithm.swap(ints2, 1, 2);
        Algorithm.swap(ints3, 0, 1);
        Algorithm.print(ints3);
            Algorithm.swap(ints3, 0, 1);
        System.out.print("\n");
        System.out.print(Algorithm.max(ints1) + " ");
        System.out.print(Algorithm.max(ints2) + " ");
        System.out.print(Algorithm.max(ints3) + " ");
        System.out.print("\n");
        System.out.print(Algorithm.min(ints1) + " ");
        System.out.print(Algorithm.min(ints2) + " ");
        System.out.print(Algorithm.min(ints3) + " ");
        System.out.print("\n");
        System.out.print(Algorithm.shortestString(strings1) + " ");
        System.out.print(Algorithm.shortestString(strings2) + " ");
        System.out.print(Algorithm.shortestString(strings3) + " ");
        System.out.print("\n");
        System.out.print(Algorithm.longestString(strings1) + " ");
        System.out.print(Algorithm.longestString(strings2) + " ");
        System.out.print(Algorithm.longestString(strings3) + " ");
        System.out.print("\n");
        System.out.print(Algorithm.largestAbsoluteDifference(ints4, ints5) + " ");
        System.out.print(Algorithm.largestAbsoluteDifference(ints3, ints4) + " ");
        System.out.print(Algorithm.largestAbsoluteDifference(ints1, ints4) + " ");
        System.out.print("\n");
        System.out.print(Algorithm.average(doubles1) + " ");
        System.out.print(Algorithm.average(doubles2) + " ");
        System.out.print(Algorithm.average(doubles3) + " ");
        System.out.print("\n");
        Algorithm.reverse(ints1);
        Algorithm.print(ints1);
        Algorithm.reverse(ints2);
        Algorithm.print(ints2);
        Algorithm.reverse(ints3);
        Algorithm.print(ints3);
        System.out.print("\n");
        System.out.print(Algorithm.consecutive(ints6) + " ");
        System.out.print(Algorithm.consecutive(ints1) + " ");
        System.out.print(Algorithm.consecutive(ints2) + " ");
        System.out.print("\n");
        System.out.print(Algorithm.firstNegative(ints7) + " ");
        System.out.print(Algorithm.firstNegative(ints1) + " ");
        System.out.print(Algorithm.firstNegative(ints2) + " ");
        System.out.print("\n");
        System.out.print(Algorithm.equivalentValue(ints8) + " ");
        System.out.print(Algorithm.equivalentValue(ints1) + " ");
        System.out.print(Algorithm.equivalentValue(ints6) + " ");
        System.out.print("\n");
        System.out.print(Algorithm.longestConsecutiveStreak(ints9, 1));
        System.out.print(Algorithm.longestConsecutiveStreak(ints6, 3));
        System.out.print(Algorithm.longestConsecutiveStreak(ints8, 2));
        System.out.print("\n");
        System.out.print(Algorithm.lastAlphabetically(strings4));
        System.out.print(Algorithm.lastAlphabetically(strings2));
        System.out.print(Algorithm.lastAlphabetically(strings3));
        System.out.print("\n");
        System.out.print(Algorithm.identialValues(ints10, ints11) + " ");
        System.out.print(Algorithm.identialValues(ints1, ints2) + " ");
        System.out.print(Algorithm.identialValues(ints1, ints3) + " ");
    }
}